import { Table } from '@/types/type'

export const initialState: Table = {
  turn: 1,
  player: {
    black: {
      name: 'player1',
      stoneNum: 2,
    },
    white: {
      name: 'player2',
      stoneNum: 2,
    },
  },
  mode: 'vsPlayer',
  cpuStrength: 'easy',
  colorCollections: {
    Basic: { table: '#090', frontStone: '#000', backStone: '#fff' },
    Striking: {
      table: '#1F2833',
      frontStone: '#66FCF1',
      backStone: '#C5C6C7',
    },
    Sophisticated: {
      table: '#5D5C61',
      frontStone: '#B1A296',
      backStone: '#7395AE',
    },
    Lively: { table: '#E7717D', frontStone: '#5D001E', backStone: '#E3E3DF' },
    Earthy: { table: '#8D8741', frontStone: '#0b8457', backStone: '#659DBD' },
    Modern: { table: '#3AAFA9', frontStone: '#17252A', backStone: '#FEFFFF' },
  },
  table: {
    1: {
      1: null,
      2: null,
      3: null,
      4: null,
      5: null,
      6: null,
      7: null,
      8: null,
    },
    2: {
      1: null,
      2: null,
      3: null,
      4: null,
      5: null,
      6: null,
      7: null,
      8: null,
    },
    3: {
      1: null,
      2: null,
      3: null,
      4: null,
      5: null,
      6: null,
      7: null,
      8: null,
    },
    4: {
      1: null,
      2: null,
      3: null,
      4: 0,
      5: 1,
      6: null,
      7: null,
      8: null,
    },
    5: {
      1: null,
      2: null,
      3: null,
      4: 1,
      5: 0,
      6: null,
      7: null,
      8: null,
    },
    6: {
      1: null,
      2: null,
      3: null,
      4: null,
      5: null,
      6: null,
      7: null,
      8: null,
    },
    7: {
      1: null,
      2: null,
      3: null,
      4: null,
      5: null,
      6: null,
      7: null,
      8: null,
    },
    8: {
      1: null,
      2: null,
      3: null,
      4: null,
      5: null,
      6: null,
      7: null,
      8: null,
    },
  },
  stone1: new Array(30).fill(0),
  stone2: new Array(30).fill(0),
  aroundStone: [
    { y: 3, x: 3 },
    { y: 3, x: 4 },
    { y: 3, x: 5 },
    { y: 3, x: 6 },
    { y: 4, x: 3 },
    { y: 4, x: 6 },
    { y: 5, x: 3 },
    { y: 5, x: 6 },
    { y: 6, x: 3 },
    { y: 6, x: 4 },
    { y: 6, x: 5 },
    { y: 6, x: 6 },
  ],
  playerChoices: [],
  aroundStoneData: [],
  tableData: [],
  cpuPosition: {
    y: 0,
    x: 0,
  },
  gameStatus: 'opening',
  gameProgress: 0,
  simulationFlag: false,
  simulationTurn: 1,
  simulationMaxEvaluationStatus: {},
  simulationTable: {},
  simulationPlayerChoices: [],
  simulationAroundStone: [],
}
